apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: kmath-post-injection
spec:
  className: run.halo.kmath.DefaultPostContentHandler
  extensionPointName: reactive-post-content-handler
  displayName: "DefaultPostContentHandler"
  description: "KMath scripts injection for post content."

---

apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: kmath-singlepage-injection
spec:
  className: run.halo.kmath.DefaultSinglePageContentHandler
  extensionPointName: reactive-singlepage-content-handler
  displayName: "DefaultSinglePageContentHandler"
  description: "KMath scripts injection for single page content."
