apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-kmath-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: select
          name: render_engine
          id: render_engine
          key: render_engine
          label: 渲染引擎
          value: katex
          help: 选择公式渲染引擎
          options:
            - label: KaTeX
              value: katex
            - label: MathJax
              value: mathjax
        - $formkit: select
          if: $get(render_engine).value === "katex"
          name: katex_output
          label: KaTeX 输出格式
          value: mathml
          help: 仅影响使用 KaTeX 渲染时的输出结构
          options:
            - label: MathML
              value: mathml
            - label: HTML
              value: html
            - label: HTML + MathML
              value: htmlAndMathml
        - $formkit: switch
          name: enable_frontend_render
          id: enable_frontend_render
          key: enable_frontend_render
          label: 启用客户端公式渲染
          help: 使用非默认编辑器、或选择 MathJax 引擎时，需要启用此项以确保前台公式正确渲染
          value: false
        - $formkit: text
          if: $get(enable_frontend_render).value === true
          name: inline_selector
          label: 行内公式 CSS 选择器
          value: "[math-inline],.katex-inline"
          help: 用于匹配行内公式的 CSS 选择器
        - $formkit: text
          if: $get(enable_frontend_render).value === true
          name: display_selector
          label: 块级公式 CSS 选择器
          value: "[math-display],.katex-block"
          help: 用于匹配块级公式的 CSS 选择器
