apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: plugin-kmath
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: Akvicor
    website: https://github.com/Akvicor
  logo: logo.png
  repo: https://github.com/Akvicor/plugin-kmath
  homepage: https://github.com/Akvicor/plugin-kmath
  issues: https://github.com/Akvicor/plugin-kmath/issues
  displayName: "KMath"
  description: "为编辑器和文章渲染提供 Math 支持"
  settingName: plugin-kmath-settings
  configMapName: plugin-kmath-configMap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Akvicor/plugin-kmath/blob/main/LICENSE"
